FROM alpine:edge
RUN apk add npm go
WORKDIR /src
COPY . .
WORKDIR /src/rconBackend/website
RUN npm install
RUN npm run build
WORKDIR /src/rconBackend
RUN go build .
RUN chmod +x go-racoon
CMD ./go-racoon

